version: '3.8'
services:
  # db:
  #   image: mongo:4.2
  #   container_name: db
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - ./data/dump:/dump
  #     - mongo-data:/data

  app:
    build: .
    image: 172.23.220.131:8083/frontoffice:6.0
    restart: always
    container_name: frontoffice
    ports:
      - '5173:5173'
    # depends_on:
    #   - db
    # volumes:
    #   - ./app:/app

# volumes:
#   mongo-data: